openapi: "3.1.0"
info:
  title: API Products
  version: "1.0"
paths:
  /api/products/:
    get:
      summary: Obtiene todos los productos
      tags:
        - Products
      responses:
        "200":
          description: Todos los productos fueron obtenidos correctamente
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Product"
        "500":
          description: Error interno del servidor

    post:
      summary: Agrega un producto a la base de datos
      tags:
        - Products
      requestBody:
        requiered: true
        content:
          application/json:
            schema:
              $ref: "#/components/requestBodies/add"
      responses:
        "200":
          description: El producto fue agregado correctamente
        "401":
          description: No tienes permiso para agregar el producto
        "500":
          description: Error interno al agregar el producto

  /api/products/{pid}:
    get:
      summary: Obtiene un producto por ID
      tags:
        - Products
      parameters:
        - name: pid
          in: path
          required: true
          description: ID del producto a buscar
          schema:
            $type: String
      responses:
        "200":
          description: El producto se obtuvo correctamente
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Product"
        "500":
          description: No se pudo obtener el producto
    put:
      summary: Actualiza un producto por ID
      tags:
        - Products
      parameters:
        - name: pid
          in: path
          requiered: true
          description: ID del producto a actualizar
          schema:
            $type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/requestBodies/add"
      responses:
        "200":
          description: El producto fue actualizado correctamente
        "500":
          description: No se pudo actulizar el producto
    delete:
      summary: Cambiar valor de status a false de un producto por ID
      tags:
        - Products
      parameters:
        - name: pid
          in: path
          required: true
          description: ID del producto a eliminar
          schema:
            $type: string
      responses:
        "200":
          description: El producto fue eliminado correctamente
        "401":
          description: No tienes permiso para agregar el producto
        "500":
          description: No se pudo eliminar el producto

components:
  schemas:
    Product:
      type: object
      properties:
        _id:
          type: string
          description: Id de Mongodb
        title:
          type: string
          description: Titulo del producto
        description:
          type: string
          description: Description del producto
        code:
          type: number
          description: Codigo unico e irrepetible de producto
        price:
          type: number
          description: Precio del producto
        status:
          type: boolean
          description: Estado de lectura del producto
        stock:
          typen: string
          description: Cantidad de unidades del producto
        category:
          type: string
          description: Categoria que pertenece el producto
        thumbnail:
          type: string
          description: Imagen url representativa del producto
      example:
        _id: ObjectId("643ef56bb0d990bb924063d4")
        title: Orange - Tangerine
        description: Ejemplo de descripcion del producto
        code: 52584-796
        price: 999
        status: true
        stock: 300
        category: Industrial
        thumbnail: http://dummyimage.com/x.png/5fa2dd/ffffff
  requestBodies:
    add:
      type: object
      properties:
        title:
          type: string
          description: Titulo del producto
        description:
          type: string
          description: Description del producto
        code:
          type: number
          description: Codigo unico e irrepetible de producto
        price:
          type: number
          description: Precio del producto
        status:
          type: boolean
          description: Estado de lectura del producto
        stock:
          typen: string
          description: Cantidad de unidades del producto
        category:
          type: string
          description: Categoria que pertenece el producto
        thumbnail:
          type: string
          description: Imagen url representativa del producto
      example:
        title: Orange - Tangerine
        description: Ejemplo de descripcion del producto
        code: 52584-796
        price: 999
        status: true
        stock: 300
        category: Industrial
        thumbnail: http://dummyimage.com/x.png/5fa2dd/ffffff
