openapi: "3.1.0"
info:
  title: API Products
  version: "1.0"
paths:
  /cart/{cid}/purchase/:
    get:
      summary: Obtiene un ticket detallado de un carrito
      tags:
        - Purchase
      parameters:
        - name: cid
          in: path
          required: true
          description: ID del carrito a finalizar compra          
          schema:
            $type: String              
      responses:
        "200":
          description: El Ticket se genero correctamente
          content:
            aplication/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Ticket"

components:
  schemas:
    Ticket:
      type: object
      properties:
        _id:
          type: string
          description: ID de Mongodb
        code:
          type: string
          description: Codigo unico del ticket
        purchase_datetime:
          type: string
          description: Fecha y hora del momento que se genero el ticket
        amount:
          type: number
          description: Monto total de la compra
        purchaser:
          type: string
          description: Email del usuario que realizo la compra
        detailedItems:
          type: array
          items:
            type: object
            properties:             
              product:
                type: string
                description: Titulo del producto
              quantity:
                type: number
                description: Cantidad del producto
              unitPrice:
                type: number
                description: Precio unitario del producto
              totalPrice:
                type: number
                description: Precio total de la cantidad de producto
      example:
        _id: ObjectId("64add4e22930950efaea6a79")
        code: d7bc130f-3f3f-4d7f-97b3-2367717e98df
        purchase_datetime: Tue Jul 11 2023 19:17:06
        amount: 2724
        purchaser: emailDelUsuario@correo.com
        detailedItems:          
          product: Sole - Fillet Prueba Modificaion
          quantity: 3
          unitPrice: 908
          totalPrice: 2724
